# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20170817_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='profesion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
