# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_prospecto_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospecto',
            name='source',
        ),
    ]
