# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_remove_prospecto_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='parametros',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
