# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_prospecto_parametros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospecto',
            old_name='parametros',
            new_name='campaign',
        ),
        migrations.AddField(
            model_name='prospecto',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='medium',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
